Run terraform fmt -check || exit 0
  terraform fmt -check || exit 0
  shell: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.EXE -command ". '{0}'"
  env:
    ARM_SUBSCRIPTION_ID: ***
    ARM_CLIENT_ID: ***
    ARM_CLIENT_SECRET: ***
    ARM_TENANT_ID: ***
    STATE_ACCOUNT: selfhostagentstorage
    STATE_CONTAINER: selfhost-container
    TERRAFORM_CLI_PATH: C:\Users\azureuser\actions-runner\_work\_temp\45c48f5c-7049-40ed-ad0b-4ad5f63f2538
  
At C:\Users\azureuser\actions-runner\_work\_temp\f813da59-2614-4811-ac04-dda719513b60.ps1:2 char:22
+ terraform fmt -check || exit 0
+                      ~~
The token '||' is not a valid statement separator in this version.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : InvalidEndOfLine
 
Error: Process completed with exit code 1.
