name: "Terraform - Hosted Agent Deploy"

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: self-hosted
    environment: production

    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.TF_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID:       ${{ secrets.TF_CLIENT_ID }}
      ARM_CLIENT_SECRET:   ${{ secrets.TF_CLIENT_SECRET }}
      ARM_TENANT_ID:       ${{ secrets.TF_TENANT_ID }}
      STATE_ACCOUNT:       selfhostagentstorage
      STATE_CONTAINER:     selfhost-container

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform (disable wrapper so exit codes work)
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13.3"
          terraform_wrapper: false

      # Optional: install Azure CLI on the runner if you want the blob/state checks
      # - name: Install Azure CLI (Windows)
      #   shell: powershell
      #   run: |
      #     Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile AzureCLI.msi
      #     Start-Process msiexec.exe -ArgumentList '/I AzureCLI.msi /qn' -Wait

      - name: Runner info
        shell: powershell
        run: |
          $os = Get-CimInstance Win32_OperatingSystem | Select-Object Caption, Version
          Write-Host "OS: $($os.Caption) $($os.Version)"
          Write-Host "PWD: $(Get-Location)"
          Write-Host "Repo: $env:GITHUB_REPOSITORY"

      - name: Terraform Init (reconfigure and upgrade)
        shell: powershell
        run: terraform init -input=false -reconfigure -upgrade

      - name: Terraform Validate
        shell: powershell
        run: terraform validate

      - name: Terraform FMT Check (non-blocking)
        shell: powershell
        run: |
          terraform fmt -check
          if ($LASTEXITCODE -ne 0) {
            Write-Host "terraform fmt would reformat files; continuing."
            $global:LASTEXITCODE = 0
          }

      - name: Terraform state (before plan)
        shell: powershell
        run: |
          terraform state list
          if ($LASTEXITCODE -ne 0) {
            Write-Host "No resources in state (yet)."
            $global:LASTEXITCODE = 0
          }

      - name: Terraform Plan (capture detailed exit code)
        id: plan
        shell: powershell
        run: |
          terraform plan -input=false -out=tfplan.bin -detailed-exitcode
          $code = $LASTEXITCODE
          Write-Host "Plan exit code: $code"
          if ($code -eq 2) {
            "has_changes=true"  | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
            exit 0
          } elseif ($code -eq 0) {
            "has_changes=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
            exit 0
          } else {
            exit $code
          }

      - name: Show Plan (human readable)
        shell: powershell
        run: terraform show -no-color tfplan.bin

      - name: Terraform Apply (only when there are changes)
        if: steps.plan.outputs.has_changes == 'true'
        shell: powershell
        run: terraform apply -input=false -auto-approve tfplan.bin

      - name: Terraform Outputs
        shell: powershell
        run: terraform output
