name: "Terraform — RG & Storage Deploy (Self-Hosted Windows)"

on:
  push:
    branches: [ main ]  # Automatically runs when pushing to main

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: self-hosted
    environment: production

    env:
      # Azure authentication via environment variables (set as repository secrets)
      ARM_SUBSCRIPTION_ID: ${{ secrets.TF_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.TF_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.TF_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.TF_TENANT_ID }}

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.13.3'  # Your version

      # 3️⃣ Initialize Terraform with backend
      - name: Terraform Init
        shell: powershell
        run: terraform init -input=false

      # 4️⃣ Validate configuration
      - name: Terraform Validate
        shell: powershell
        run: terraform validate

      # 5️⃣ Terraform Plan (no -var inline for Azure credentials)
      - name: Terraform Plan
        shell: powershell
        run: terraform plan -out=tfplan-rg-storage.bin

      # 6️⃣ Terraform Apply
      - name: Terraform Apply
        shell: powershell
        run: terraform apply -auto-approve tfplan-rg-storage.bin

      # 7️⃣ Show outputs
      - name: Terraform Outputs
        shell: powershell
        run: terraform output
