name: "Terraform - Deploy RG & Storage"

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: self-hosted

    env:
      TF_WORKING_DIR: '.'
      TF_PLAN_FILE: 'tfplan-rg-storage.bin'
      TF_STATE_FILE: 'rg-storage.tfstate'

      # ✅ Azure environment variables (used automatically by Terraform)
      ARM_SUBSCRIPTION_ID: ${{ secrets.TF_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID:       ${{ secrets.TF_CLIENT_ID }}
      ARM_CLIENT_SECRET:   ${{ secrets.TF_CLIENT_SECRET }}
      ARM_TENANT_ID:       ${{ secrets.TF_TENANT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.13.3'

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -backend-config="path=${{ env.TF_STATE_FILE }}"

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -out="${{ env.TF_PLAN_FILE }}"

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve "${{ env.TF_PLAN_FILE }}"

      - name: Show Terraform Outputs
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform output
